import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import BottomNav from "@/components/layout/BottomNav";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className="font-sans">
        <div className="max-w-107.5 mx-auto min-h-dvh">
          <Header />
          <main className="px-4 pb-24 pt-4 h-[3000px] bg-amber-200">
            {children}
          </main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
