import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import BottomNav from "@/components/layout/BottomNav";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className="font-sans">
        <div className="max-w-107.5 md:max-w-240 mx-auto min-h-dvh flex flex-col">
          <Header />
          <main className="flex-1 px-4 pb-24 pt-4 md:pb-6">{children}</main>
          <BottomNav />
          <footer className="hidden md:flex w-full items-center justify-center border-t border-border py-4 text-sm text-muted-foreground">
            {new Date().getFullYear()} | Copyright Eileen
          </footer>
        </div>
      </body>
    </html>
  );
}
